// Auto-generated by the Klar React generator. Do not edit by hand.
// Per-entity config files in this folder import these types.
// The sandbox sub-agent (Step 0) is allowed to write the per-entity
// config files but must not change the type definitions here.

export type DefaultSpec =
  /** withTime: true emits YYYY-MM-DDT00:00 (needed for date/datetimeminute). */
  | { kind: 'today'; withTime?: boolean }
  | { kind: 'todayOffset'; days: number; withTime?: boolean }
  | { kind: 'literal'; value: string | number | boolean }
  /** The calendar year as a number, resolved at mount. A year pinned as a
   *  literal is right on the day it is written and wrong from 1 January. */
  | { kind: 'currentYear' }
  /** For lookup/select|radio fields. The shape matches LookupValue. */
  | { kind: 'lookup'; key: string; label: string };

export type ComputedOperand =
  | { kind: 'field';    key: string }
  | { kind: 'literal';  value: number }
  /** Follow an applookup field in this form, read a numeric field from the resolved record. */
  | { kind: 'applookup'; ownKey: string; lookupKey: string }
  /** Difference between two date fields in this form, expressed in days or hours. */
  | { kind: 'dateDiff';  from: string; to: string; unit: 'days' | 'hours' };

/**
 * A ComputedSpec is a tree: each side is either a leaf Operand or another
 * ComputedSpec. Use `interface` (not `type`) so the recursive reference type-checks.
 * Example (Zimmer × Nächte + Zusatzleistung pauschal):
 *   {
 *     op: 'add',
 *     left:  { op: 'mul',
 *              left:  { kind: 'applookup', ownKey: 'zimmer', lookupKey: 'tagespreis' },
 *              right: { kind: 'dateDiff',  from: 'anreise', to: 'abreise', unit: 'days' } },
 *     right: { kind: 'applookup', ownKey: 'zusatzleistungen', lookupKey: 'preis' },
 *   }
 */
export interface ComputedSpec {
  op: 'add' | 'sub' | 'mul' | 'div';
  left: ComputedOperand | ComputedSpec;
  right: ComputedOperand | ComputedSpec;
}

/**
 * Runtime context for evalComputed. `lookupLists` maps an applookup field key
 * in the current form to the resolved record list (the list prop passed to
 * the dialog). The shape is intentionally loose — strictly-typed `<Entity>[]`
 * props are assignable here without casting. evalComputed inspects each entry
 * defensively at runtime: r?.record_id and r?.fields are both checked.
 */
export type ComputedContext = {
  lookupLists: Record<string, unknown>;
};

/**
 * Sandbox-style helper API passed to ComputedFn. Bounded surface — the
 * function has access ONLY to these helpers, the current form data, and
 * pure arithmetic. No fetch, no DOM, no localStorage from this surface.
 */
export interface ComputedCtx {
  /**
   * Read a form field AS A NUMBER — the accessor for arithmetic. Missing,
   * empty or non-numeric values become 0, so no `?? 0` and no `Number(…)`
   * wrapper are needed:  `ctx.num('preis') * 1.19`.
   */
  num(key: string): number;
  /**
   * Read a raw field value from the current form — for non-numeric reads
   * (string compares, presence checks). Typed `any` deliberately: the values
   * are dynamic form data, and an `unknown` return only ever bought TS2362
   * build breaks in generated formula code. Use `num()` for arithmetic.
   * Reads REAL form fields only — other `computed` keys are not in here.
   */
  field(key: string): any;
  /** Resolve an applookup field → numeric field on the target record. Returns null on miss. */
  applookup(ownKey: string, lookupKey: string): number | null;
  /** Read an arbitrary (non-numeric) lookup field from a resolved applookup target. */
  applookupAny(ownKey: string, lookupKey: string): unknown;
  /** Resolve a lookup/select|radio field to its `key` string (for switch logic). */
  lookupKey(key: string): string | null;
  /** Difference between two date fields in days (default) or hours. Null when either is missing. */
  dateDiff(fromKey: string, toKey: string, unit?: 'days' | 'hours'): number | null;
  // NOTE: there is deliberately no `addDays` — it returned a Date, and a
  // ComputedFn can only ever return a number, so the only thing the helper
  // ever produced was a TS2322 (live: a `faelligkeitsdatum` entry that built
  // a 'yyyy-MM-dd' string from it). Date PREFILLS belong in `defaults`
  // ({ kind: 'todayOffset', days: n }), never in `computed`.
  /**
   * Sum a per-item value over a multilookup field. The callback receives the
   * resolved record (with its fields). Items that throw or return non-finite
   * are skipped — total stays a finite number.
   */
  sumOver(
    multilookupKey: string,
    perItem: (item: { record_id: string; fields: Record<string, unknown> }) => number,
  ): number;
}

/**
 * Hybrid escape hatch: when a formula needs branching, loops, or per-day
 * conditionals that the declarative spec can't express, the sub-agent may
 * emit a function instead. It MUST be pure: only fields + ctx in, number|null out.
 * Exceptions and non-finite returns are silently swallowed → no suggestion shown.
 *
 * NUMBERS ONLY. `computed` computes amounts, counts and durations — never a
 * date string, never a label. A string return is a TS2322 that costs a build
 * round, so parse-formulas drops such an entry before tsc sees it.
 */
export type ComputedFn = (
  fields: Record<string, unknown>,
  ctx: ComputedCtx,
) => number | null | undefined;

/**
 * Either a declarative spec tree (with `op`), an inline function, OR a
 * bare leaf operand. The bare-leaf case covers single-lookup formulas like
 * `applookup(leistung, preis)` where no arithmetic is needed — parse-formulas
 * expands these to a single ComputedOperand. `resolveExpr` and `extractFieldDeps`
 * already walk operand-or-spec uniformly, so widening here is type-only.
 */
export type Computed = ComputedSpec | ComputedFn | ComputedOperand;

/**
 * Per-field number-input rules. Sub-Agent (Step 0) decides per field based on
 * domain semantics. Missing entry = default rules apply (min=0, no max).
 *
 *   • allowNegative: true  → input accepts negative values (Saldo, Differenz,
 *                            Temperatur, Bewertung mit Minus, Geo-Koordinate).
 *                            Default false: min=0 is enforced.
 *   • max: 100             → upper bound (typical for percent fields).
 */
export type NumberFieldConfig = {
  allowNegative?: boolean;
  max?: number;
};

/**
 * One slot in fieldOrder: either a single field key, or a row of 2+ keys
 * to be rendered side-by-side in a CSS grid. `cols` is a CSS
 * grid-template-columns string (e.g. "1fr 2fr"); default = equal columns.
 *
 * The Python generator (layout_heuristic.py) emits row-objects for known
 * adjacent pairs (PLZ+Ort, Straße+Hausnummer, Vorname+Nachname, Date-Range).
 * The sub-agent must treat row-objects as ATOMS — it may reorder them
 * between other slots, but must not split a row into separate strings.
 */
export type FieldOrderItem = string | { row: string[]; cols?: string };

export type FormEnhancements = {
  /**
   * Preferred render order of field keys. Unknown keys are appended in
   * their original order. `null` keeps the source order. Each slot is
   * either a single key (string) or a row of side-by-side keys.
   */
  fieldOrder: FieldOrderItem[] | null;
  /** Default values applied on create (never on edit). */
  defaults: Record<string, DefaultSpec>;
  /** Derived numeric fields. Validated at runtime; bad entries are ignored. */
  computed: Record<string, Computed>;
  /** Per-field number rules (min/max/allowNegative). Optional. */
  numberFields?: Record<string, NumberFieldConfig>;
};

/**
 * Returns HTML input props (min, max) for a number field. Default is min=0
 * unless the field is explicitly marked allowNegative.
 */
export function numberInputProps(
  fe: FormEnhancements,
  key: string,
): { min?: number; max?: number } {
  const c = fe.numberFields?.[key];
  const out: { min?: number; max?: number } = {};
  if (!c?.allowNegative) out.min = 0;
  if (c?.max !== undefined) out.max = c.max;
  return out;
}

/**
 * Clamps a freshly-typed number into the field's allowed range. Returns
 * undefined when the input is empty (matches the existing free-clear UX).
 */
export function clampNumberValue(
  fe: FormEnhancements,
  key: string,
  raw: string,
): number | undefined {
  if (!raw) return undefined;
  const n = Number(raw);
  if (!Number.isFinite(n)) return undefined;
  const c = fe.numberFields?.[key];
  let v = n;
  if (!c?.allowNegative && v < 0) v = 0;
  if (c?.max !== undefined && v > c.max) v = c.max;
  return v;
}

/**
 * Apply a fieldOrder to a list of source keys, preserving unknown keys.
 * Filters out keys that are not in sourceKeys (both inside rows and as
 * single slots). Rows that lose all members are dropped; rows that lose
 * all but one member collapse to a plain string.
 */
export function applyFieldOrder(
  sourceKeys: string[],
  order: FieldOrderItem[] | null,
): FieldOrderItem[] {
  if (!order || order.length === 0) return sourceKeys;
  const known = new Set<string>();
  const out: FieldOrderItem[] = [];
  for (const item of order) {
    if (typeof item === 'string') {
      if (sourceKeys.includes(item) && !known.has(item)) {
        out.push(item);
        known.add(item);
      }
      continue;
    }
    const validRow = item.row.filter((k) => sourceKeys.includes(k) && !known.has(k));
    if (validRow.length === 0) continue;
    if (validRow.length === 1) {
      out.push(validRow[0]);
      known.add(validRow[0]);
      continue;
    }
    out.push({ ...item, row: validRow });
    validRow.forEach((k) => known.add(k));
  }
  for (const k of sourceKeys) if (!known.has(k)) out.push(k);
  return out;
}

/** Flatten a FieldOrderItem list into the plain key sequence. */
export function flattenFieldOrder(items: FieldOrderItem[]): string[] {
  const out: string[] = [];
  for (const it of items) {
    if (typeof it === 'string') out.push(it);
    else out.push(...it.row);
  }
  return out;
}

/** Resolve a default spec to a concrete value at component mount. */
export function resolveDefault(spec: DefaultSpec): unknown {
  if (spec.kind === 'today') {
    const ymd = new Date().toISOString().slice(0, 10);
    return spec.withTime ? `${ymd}T00:00` : ymd;
  }
  if (spec.kind === 'todayOffset') {
    const d = new Date();
    d.setDate(d.getDate() + spec.days);
    const ymd = d.toISOString().slice(0, 10);
    return spec.withTime ? `${ymd}T00:00` : ymd;
  }
  if (spec.kind === 'currentYear') {
    return new Date().getFullYear();
  }
  if (spec.kind === 'lookup') {
    return { key: spec.key, label: spec.label };
  }
  return spec.value;
}

/**
 * Apply defaults to a base form-data object. Only fills slots that are
 * undefined / null / empty string — never overwrites a user-supplied value.
 * Use only for fresh create dialogs (skip when defaultValues comes from edit).
 */
export function applyDefaults(
  base: Record<string, unknown>,
  defaults: Record<string, DefaultSpec>,
): Record<string, unknown> {
  const out = { ...base };
  for (const [key, spec] of Object.entries(defaults)) {
    const v = out[key];
    if (v !== undefined && v !== null && v !== '') continue;
    out[key] = resolveDefault(spec);
  }
  return out;
}

/**
 * Find the resolved target record for an applookup field value in the form.
 * Used by both `resolveExpr` and the inline applookup-reference renderer.
 * Returns null when the field is empty, the URL is malformed, or the
 * referenced record isn't in the loaded list yet.
 */
function resolveLookupRecord(
  ownKey: string,
  url: unknown,
  ctx: ComputedContext,
): { record_id: string; fields: Record<string, unknown> } | null {
  if (typeof url !== 'string' || url === '') return null;
  const recordId = url.split('/').pop();
  if (!recordId) return null;
  const list = ctx.lookupLists[ownKey];
  if (!Array.isArray(list)) return null;
  const rec = list.find(
    (r): r is { record_id: string; fields: Record<string, unknown> } =>
      !!r &&
      typeof r === 'object' &&
      (r as { record_id?: unknown }).record_id === recordId &&
      typeof (r as { fields?: unknown }).fields === 'object',
  );
  return rec ?? null;
}

/**
 * Resolve a single applookup reference (ownKey → lookupKey) to its current
 * numeric value from the loaded target record. Returns null on miss / non-
 * numeric. Used by the inline applookup-hint renderer in the dialog so the
 * user can see WHICH value the formula will pull from the selected lookup.
 */
export function resolveApplookupRef(
  ownKey: string,
  lookupKey: string,
  data: Record<string, unknown>,
  ctx: ComputedContext = { lookupLists: {} },
): number | null {
  const rec = resolveLookupRecord(ownKey, data[ownKey], ctx);
  if (!rec) return null;
  const v = rec.fields[lookupKey];
  const n = typeof v === 'number' ? v : Number(v);
  return Number.isFinite(n) ? n : null;
}

/**
 * Recursively resolve a computed expression node (operand leaf or nested spec)
 * to a raw number. Returns NaN on any failure so the caller can fail-soft.
 *
 * Partial-input behavior:
 *  - `add`/`sub`: a missing (NaN) operand counts as 0, so a sum updates
 *    progressively as operands come in. If BOTH sides are NaN the result is
 *    still NaN (no suggestion yet).
 *  - `mul`/`div`: strict — a missing operand makes the result NaN, because
 *    "unknown × something" has no sensible default.
 */
function resolveExpr(
  expr: ComputedOperand | ComputedSpec,
  data: Record<string, unknown>,
  ctx: ComputedContext,
): number {
  // Nested ComputedSpec: 'op' property discriminates.
  if ('op' in expr) {
    const a = resolveExpr(expr.left, data, ctx);
    const b = resolveExpr(expr.right, data, ctx);
    if (expr.op === 'add' || expr.op === 'sub') {
      if (!Number.isFinite(a) && !Number.isFinite(b)) return NaN;
      const aN = Number.isFinite(a) ? a : 0;
      const bN = Number.isFinite(b) ? b : 0;
      return expr.op === 'add' ? aN + bN : aN - bN;
    }
    if (!Number.isFinite(a) || !Number.isFinite(b)) return NaN;
    return expr.op === 'mul' ? a * b : (b === 0 ? NaN : a / b);
  }
  // Leaf operand.
  if (expr.kind === 'literal') return expr.value;
  if (expr.kind === 'field') {
    const v = data[expr.key];
    return typeof v === 'number' ? v : Number(v);
  }
  if (expr.kind === 'applookup') {
    const rec = resolveLookupRecord(expr.ownKey, data[expr.ownKey], ctx);
    if (!rec) return NaN;
    const v = rec.fields[expr.lookupKey];
    return typeof v === 'number' ? v : Number(v);
  }
  if (expr.kind === 'dateDiff') {
    const a = data[expr.from];
    const b = data[expr.to];
    if (typeof a !== 'string' || typeof b !== 'string' || !a || !b) return NaN;
    const ms = new Date(b).getTime() - new Date(a).getTime();
    if (!Number.isFinite(ms)) return NaN;
    const div = expr.unit === 'hours' ? 3_600_000 : 86_400_000;
    return Math.max(0, Math.round(ms / div));
  }
  return NaN;
}

/** Build the helper API for ComputedFn from raw form data + lookup context. */
function buildComputedCtx(
  data: Record<string, unknown>,
  ctx: ComputedContext,
): ComputedCtx {
  return {
    num(key) {
      const v = data[key];
      if (typeof v === 'number') return Number.isFinite(v) ? v : 0;
      if (typeof v !== 'string' || !v.trim()) return 0;
      const n = Number(v);
      return Number.isFinite(n) ? n : 0;
    },
    field(key) {
      return data[key];
    },
    applookup(ownKey, lookupKey) {
      const rec = resolveLookupRecord(ownKey, data[ownKey], ctx);
      if (!rec) return null;
      const v = rec.fields[lookupKey];
      const n = typeof v === 'number' ? v : Number(v);
      return Number.isFinite(n) ? n : null;
    },
    applookupAny(ownKey, lookupKey) {
      const rec = resolveLookupRecord(ownKey, data[ownKey], ctx);
      return rec ? rec.fields[lookupKey] : undefined;
    },
    lookupKey(key) {
      const v = data[key];
      if (v && typeof v === 'object' && 'key' in (v as Record<string, unknown>)) {
        const k = (v as { key?: unknown }).key;
        return typeof k === 'string' ? k : null;
      }
      return typeof v === 'string' ? v : null;
    },
    dateDiff(fromKey, toKey, unit = 'days') {
      const a = data[fromKey];
      const b = data[toKey];
      if (typeof a !== 'string' || typeof b !== 'string' || !a || !b) return null;
      const ms = new Date(b).getTime() - new Date(a).getTime();
      if (!Number.isFinite(ms)) return null;
      const div = unit === 'hours' ? 3_600_000 : 86_400_000;
      return Math.max(0, Math.round(ms / div));
    },
    sumOver(multilookupKey, perItem) {
      const urls = data[multilookupKey];
      if (!Array.isArray(urls)) return 0;
      let total = 0;
      for (const url of urls) {
        const rec = resolveLookupRecord(multilookupKey, url, ctx);
        if (!rec) continue;
        try {
          const v = perItem({ record_id: rec.record_id, fields: rec.fields });
          if (Number.isFinite(v)) total += v;
        } catch {
          // swallow per-item errors; skip and continue
        }
      }
      return total;
    },
  };
}

/**
 * Evaluate a computed entry against the current form data + lookup context.
 *
 * Accepts BOTH the declarative spec tree AND an inline function. The function
 * form is wrapped in try/catch and any thrown error or non-finite return is
 * coerced to null (no suggestion shown).
 */
export function evalComputed(
  computed: Computed,
  data: Record<string, unknown>,
  ctx: ComputedContext = { lookupLists: {} },
): number | null {
  if (typeof computed === 'function') {
    try {
      const v = computed(data, buildComputedCtx(data, ctx));
      if (v == null || !Number.isFinite(v)) return null;
      return Math.round((v as number) * 100) / 100;
    } catch {
      return null;
    }
  }
  const v = resolveExpr(computed, data, ctx);
  if (!Number.isFinite(v)) return null;
  // Round to 2 decimals to avoid noise like 89.69999999999999 from floats.
  return Math.round(v * 100) / 100;
}

/**
 * Extrahiert die Field-Keys, von denen ein Computed direkt abhängt. Wird im
 * EntityDialog genutzt, um pro Eingabe-Feld inline die abhängigen Berechnungen
 * anzuzeigen ("→ Arbeitskosten 170 €" unter "Arbeitsstunden"). MODUS-2-
 * Funktionen sind opak — wir geben eine leere Liste zurück.
 */
export function extractFieldDeps(spec: Computed): Set<string> {
  const deps = new Set<string>();
  if (typeof spec === 'function') return deps;
  function walk(node: ComputedOperand | ComputedSpec): void {
    if ('op' in node) {
      walk(node.left);
      walk(node.right);
      return;
    }
    if (node.kind === 'field') deps.add(node.key);
    else if (node.kind === 'applookup') deps.add(node.ownKey);
    else if (node.kind === 'dateDiff') { deps.add(node.from); deps.add(node.to); }
  }
  walk(spec);
  return deps;
}

/**
 * Liste der applookup-Referenzen pro `ownKey` (Lookup-Feldname im Form).
 * Jeder Eintrag = ein konkretes `applookup(ownKey, lookupKey)`-Vorkommen
 * in einer beliebigen Computed-Formel. Pro (ownKey, lookupKey)-Paar nur
 * einmal — verschiedene lookupKeys vom selben ownKey landen aber alle in
 * der Liste, damit der User alle Werte sieht, die vom Target gezogen werden
 * (z.B. einzelpreis UND karten10_preis UND monatsabo_preis bei Kurs).
 */
export type ApplookupRef = { lookupKey: string };

/**
 * Walk all MODUS-1 spec-trees in `computed` and collect every applookup
 * operand. Returns Map<ownKey, ApplookupRef[]> deduped per (ownKey, lookupKey).
 *
 * MODUS-2 (arrow functions) are opaque to spec-walking — for those, the
 * build-time `computedApplookupRefs` map (emitted by parse-formulas.mjs) is
 * the source of truth and is merged in by the dialog at render time.
 */
export function extractApplookupRefs(
  computed: Record<string, Computed>,
): Record<string, ApplookupRef[]> {
  const seen: Record<string, Set<string>> = {};
  function walk(node: ComputedOperand | ComputedSpec): void {
    if ('op' in node) { walk(node.left); walk(node.right); return; }
    if (node.kind === 'applookup') {
      (seen[node.ownKey] ||= new Set()).add(node.lookupKey);
    }
  }
  for (const spec of Object.values(computed)) {
    if (typeof spec === 'function') continue;
    walk(spec);
  }
  const out: Record<string, ApplookupRef[]> = {};
  for (const [ownKey, set] of Object.entries(seen)) {
    out[ownKey] = [...set].map(lookupKey => ({ lookupKey }));
  }
  return out;
}

/**
 * Merge MODUS-1 refs (from extractApplookupRefs) with MODUS-2 refs (from
 * parse-formulas' computedApplookupRefs export). Dedup per (ownKey, lookupKey).
 */
export function mergeApplookupRefs(
  ...sources: Array<Record<string, ApplookupRef[]> | undefined>
): Record<string, ApplookupRef[]> {
  const seen: Record<string, Set<string>> = {};
  for (const src of sources) {
    if (!src) continue;
    for (const [ownKey, refs] of Object.entries(src)) {
      const set = seen[ownKey] ||= new Set();
      for (const ref of refs) set.add(ref.lookupKey);
    }
  }
  const out: Record<string, ApplookupRef[]> = {};
  for (const [ownKey, set] of Object.entries(seen)) {
    out[ownKey] = [...set].map(lookupKey => ({ lookupKey }));
  }
  return out;
}

/**
 * Klassifiziert die Computed-Felder einer FormEnhancements-Config in drei Eimer:
 *
 *   • `anchors[inputKey]` — Computeds, die direkt aus Eingabe-Feldern berechnet
 *     werden (z.B. arbeitskosten = stundensatz × arbeitsstunden). Werden
 *     INLINE unter dem letzten beteiligten Eingabe-Feld angezeigt.
 *   • `aggregates` — Computeds, die andere Computeds aggregieren (netto, mwst).
 *     Werden im Summary-Block am Form-Ende angezeigt.
 *   • `finalTotal` — der finale Total-Wert (typischerweise "brutto*"/"gesamt*").
 *     Wird PROMINENT als Endbetrag dargestellt. Fallback: letztes Aggregate.
 *
 * Reihenfolge folgt Insertion-Order in `formEnhancements.computed`.
 */
export type ComputedLayout = {
  anchors: Record<string, string[]>;
  aggregates: string[];
  finalTotal: string | null;
};

export function classifyComputed(
  fe: FormEnhancements,
  inputFields: string[],
  externalDeps?: Record<string, string[]>,
): ComputedLayout {
  const anchors: Record<string, string[]> = {};
  const aggregates: string[] = [];
  const computedKeys = new Set(Object.keys(fe.computed));
  for (const [cKey, spec] of Object.entries(fe.computed)) {
    // Build-time deps (extracted from MODUS-2 arrow function bodies via regex
    // in scripts/parse-formulas.mjs) take precedence over the static spec
    // walk. This lets us anchor MODUS-2 computeds inline instead of dumping
    // them all into the aggregate sink.
    const deps = externalDeps && externalDeps[cKey]
      ? new Set(externalDeps[cKey])
      : extractFieldDeps(spec);
    // Aggregat = at least one dep is itself a computed key. For MODUS-2 with
    // no externalDeps the previous heuristic (function ⇒ aggregate) still
    // applies because extractFieldDeps returns empty for functions.
    const hasExternal = !!(externalDeps && externalDeps[cKey]);
    const isAggregate = (!hasExternal && typeof spec === 'function')
      || [...deps].some(d => computedKeys.has(d));
    if (isAggregate) { aggregates.push(cKey); continue; }
    // Anker = letzter Input in fieldOrder, der in deps steht.
    let anchor: string | null = null;
    for (let i = inputFields.length - 1; i >= 0; i--) {
      if (deps.has(inputFields[i])) { anchor = inputFields[i]; break; }
    }
    if (anchor) {
      if (!anchors[anchor]) anchors[anchor] = [];
      anchors[anchor].push(cKey);
    } else {
      // Direct-Computed ohne erreichbaren Anker (z.B. nur applookup ohne mengen-Feld).
      aggregates.push(cKey);
    }
  }
  // Final-Total: letztes Aggregate mit "brutto"/"endsumme"/"endpreis" im Key;
  // sonst das letzte Aggregate überhaupt.
  let finalTotal: string | null = null;
  for (let i = aggregates.length - 1; i >= 0; i--) {
    if (/brutto|endsumme|endpreis|gesamt_brutto/i.test(aggregates[i])) { finalTotal = aggregates[i]; break; }
  }
  if (!finalTotal && aggregates.length > 0) finalTotal = aggregates[aggregates.length - 1];
  return { anchors, aggregates: aggregates.filter(k => k !== finalTotal), finalTotal };
}
